[2023-11-17T02:17:13.713+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=data_ingestion_gcs_dag/run_id=scheduled__2023-11-16T00:00:00+00:00/task_id=bigquery_external_table_task permission to 509
[2023-11-17T02:17:13.745+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=data_ingestion_gcs_dag/run_id=scheduled__2023-11-16T00:00:00+00:00/task_id=bigquery_external_table_task permission to 509
[2023-11-17T02:17:13.769+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.bigquery_external_table_task scheduled__2023-11-16T00:00:00+00:00 [queued]>
[2023-11-17T02:17:13.780+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.bigquery_external_table_task scheduled__2023-11-16T00:00:00+00:00 [queued]>
[2023-11-17T02:17:13.781+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-11-17T02:17:13.798+0000] {taskinstance.py:1382} INFO - Executing <Task(BigQueryCreateExternalTableOperator): bigquery_external_table_task> on 2023-11-16 00:00:00+00:00
[2023-11-17T02:17:13.807+0000] {standard_task_runner.py:57} INFO - Started process 14384 to run task
[2023-11-17T02:17:13.810+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'bigquery_external_table_task', 'scheduled__2023-11-16T00:00:00+00:00', '--job-id', '120', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmpg5kylqhu']
[2023-11-17T02:17:13.813+0000] {standard_task_runner.py:85} INFO - Job 120: Subtask bigquery_external_table_task
[2023-11-17T02:17:13.826+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:193: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2023-11-17T02:17:13.865+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=data_ingestion_gcs_dag/run_id=scheduled__2023-11-16T00:00:00+00:00/task_id=bigquery_external_table_task permission to 509
[2023-11-17T02:17:13.868+0000] {task_command.py:416} INFO - Running <TaskInstance: data_ingestion_gcs_dag.bigquery_external_table_task scheduled__2023-11-16T00:00:00+00:00 [running]> on host 2952db3161f1
[2023-11-17T02:17:13.988+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_ingestion_gcs_dag' AIRFLOW_CTX_TASK_ID='bigquery_external_table_task' AIRFLOW_CTX_EXECUTION_DATE='2023-11-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-16T00:00:00+00:00'
[2023-11-17T02:17:13.991+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2023-11-17T02:17:13.992+0000] {connection.py:232} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2023-11-17T02:17:13.994+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2023-11-17T02:17:14.527+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcs_dag, task_id=bigquery_external_table_task, execution_date=20231116T000000, start_date=20231117T021713, end_date=20231117T021714
[2023-11-17T02:17:14.588+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-17T02:17:14.610+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
